#!/usr/bin/env python3
"""
GENERATOR — writes pages/stocks/src/data/closes/<symbol>.js, one per
instrument, and pages/stocks/src/data/instruments.js, the list the page reads.

Every daily close Yahoo Finance holds for each instrument below. The page
loads one instrument's closes only as its chart nears the viewport, so the
list module carries a loader per instrument rather than the data itself —
the eighty-odd thousand sessions never land in the page's own bundle.

The fetching lives in scripts/yahoo_daily.py, shared with /tmobile — read its
docstring: null closes, mid-session runs and split adjustment each produce a
chart that looks right and is not.

Two things specific to this set:

1.  SMH's history before 2011 is Merrill Lynch's Semiconductor HOLDRS, which
    VanEck's ETF took over the ticker from. Yahoo splices the two, and so does
    the chart; the page says so.

2.  XLF's 1231:1000 "split" of 2016-09-19 is the spin-off of the real-estate
    names into XLRE, booked as a split so the price series stays continuous.

To add an instrument: add it to INSTRUMENTS and run this. The page sorts by
label itself, so the order here does not matter.

Run:  python3 pages/stocks/scripts/fetch-daily-closes.py
      python3 pages/stocks/scripts/fetch-daily-closes.py SPY QQQ   # just these
"""

import argparse
import json
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / 'scripts'))
from yahoo_daily import HoleInSeries, fetch_daily_closes, row_lines  # noqa: E402

DATA = Path(__file__).resolve().parents[1] / 'src' / 'data'

# (Yahoo symbol, the label the page files it under, a plain-English name)
INSTRUMENTS = [
    ('BRK-B', 'BRK-B', 'Berkshire Hathaway, class B'),
    ('BTC-USD', 'Bitcoin', 'Bitcoin in US dollars'),
    ('ETH-USD', 'Ethereum', 'Ethereum in US dollars'),
    ('QQQ', 'QQQ', 'Nasdaq-100'),
    ('SMH', 'SMH', 'Semiconductors'),
    ('SPY', 'SPY', 'S&P 500'),
    ('XLB', 'XLB', 'Materials sector'),
    ('XLE', 'XLE', 'Energy sector'),
    ('XLF', 'XLF', 'Financials sector'),
    ('XLK', 'XLK', 'Technology sector'),
    ('XLP', 'XLP', 'Consumer staples sector'),
    ('XLRE', 'XLRE', 'Real estate sector'),
    ('XLU', 'XLU', 'Utilities sector'),
    ('XLY', 'XLY', 'Consumer discretionary sector'),
]

HEADER = '/* GENERATED by pages/stocks/scripts/fetch-daily-closes.py — do not hand-edit. */'


def slug(symbol):
    return symbol.lower()


def closes_module(rows, info):
    return '\n'.join([
        HEADER,
        '',
        f'export const META = {json.dumps(info, separators=(", ", ": "))};',
        '',
        '/** [date, close] for every session, oldest first. */',
        'export const CLOSES = [',
        *row_lines(rows),
        '];',
        '',
    ])


def instruments_module(infos):
    lines = [
        HEADER,
        '',
        '/**',
        ' * Every instrument on the page, with what is known about its series before',
        ' * the series itself is loaded. `load` imports that one instrument\'s closes.',
        ' */',
        'export const INSTRUMENTS = [',
    ]
    for symbol, label, blurb in INSTRUMENTS:
        info = infos[symbol]
        entry = {
            'symbol': symbol, 'label': label, 'blurb': blurb, 'name': info['name'],
            'first': info['first'], 'last': info['last'], 'sessions': info['sessions'],
            'fetched': info['fetched'],
        }
        body = json.dumps(entry, separators=(', ', ': '))[1:-1]
        lines.append(f"  {{ {body}, load: () => import('./closes/{slug(symbol)}.js') }},")
    lines += ['];', '']
    return '\n'.join(lines)


def read_info(symbol):
    """An instrument's metadata as last written, for a partial run."""
    text = (DATA / 'closes' / f'{slug(symbol)}.js').read_text()
    line = next(l for l in text.splitlines() if l.startswith('export const META = '))
    return json.loads(line[len('export const META = '):].rstrip(';'))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('symbols', nargs='*', help='refresh only these (default: all)')
    args = parser.parse_args()

    known = {symbol for symbol, _, _ in INSTRUMENTS}
    wanted = args.symbols or [symbol for symbol, _, _ in INSTRUMENTS]
    unknown = set(wanted) - known
    if unknown:
        sys.exit(f'Not in INSTRUMENTS: {", ".join(sorted(unknown))}')

    (DATA / 'closes').mkdir(parents=True, exist_ok=True)
    infos = {}
    for symbol in wanted:
        try:
            rows, info = fetch_daily_closes(symbol, log=lambda m: print(m, file=sys.stderr))
        except HoleInSeries as error:
            sys.exit(f'{error}; refusing to write a series with a hole in it.')
        (DATA / 'closes' / f'{slug(symbol)}.js').write_text(closes_module(rows, info))
        infos[symbol] = info
        print(f'{symbol}: {info["sessions"]} sessions, {info["first"]} to {info["last"]}',
              file=sys.stderr)
        time.sleep(0.5)

    for symbol in known - set(wanted):
        infos[symbol] = read_info(symbol)
    (DATA / 'instruments.js').write_text(instruments_module(infos))


if __name__ == '__main__':
    main()
