name: Lock Down Lambda URL with CloudFront OAC

on:
  workflow_dispatch:

jobs:
  add-oac:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create CloudFront OAC for Lambda
        id: create-oac
        run: |
          OAC_OUTPUT=$(aws cloudfront create-origin-access-control \
            --origin-access-control-config '{
              "Name": "alanmarcero-lambda-oac",
              "Description": "OAC for alanmarcero.com Lambda API origin",
              "SigningProtocol": "sigv4",
              "SigningBehavior": "always",
              "OriginAccessControlOriginType": "lambda"
            }')
          OAC_ID=$(echo "$OAC_OUTPUT" | jq -r '.OriginAccessControl.Id')
          echo "OAC_ID=$OAC_ID" >> "$GITHUB_OUTPUT"
          echo "Created OAC: $OAC_ID"

      - name: Switch Lambda Function URL auth to AWS_IAM
        run: |
          aws lambda update-function-url-config \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --auth-type AWS_IAM
          echo "Lambda Function URL auth switched to AWS_IAM"

      - name: Grant CloudFront permission to invoke Lambda
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          aws lambda add-permission \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --statement-id "AllowCloudFrontServicePrincipal" \
            --action "lambda:InvokeFunctionUrl" \
            --principal "cloudfront.amazonaws.com" \
            --source-arn "arn:aws:cloudfront::${ACCOUNT_ID}:distribution/${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}"
          echo "Lambda resource policy updated"

      - name: Attach OAC to lambda-api origin in CloudFront
        run: |
          aws cloudfront get-distribution-config \
            --id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --output json > cf-config.json

          jq -r '.ETag' cf-config.json > etag.txt
          jq '.DistributionConfig' cf-config.json > dist-config.json

          OAC_ID="${{ steps.create-oac.outputs.OAC_ID }}"
          jq --arg oac "$OAC_ID" \
            '(.Origins.Items[] | select(.Id == "lambda-api")).OriginAccessControlId = $oac' \
            dist-config.json > dist-config-updated.json

          ETAG=$(cat etag.txt)
          aws cloudfront update-distribution \
            --id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --if-match "$ETAG" \
            --distribution-config file://dist-config-updated.json
          echo "CloudFront distribution update initiated"

      - name: Verify setup
        run: |
          echo "=== OAC Setup Complete ==="
          echo "OAC ID: ${{ steps.create-oac.outputs.OAC_ID }}"
          echo ""
          echo "Lambda Function URL now requires AWS_IAM auth."
          echo "CloudFront will sign requests via OAC (SigV4)."
          echo ""
          echo "CloudFront distribution is updating (5-15 minutes)."
          echo "Check status:"
          echo "  aws cloudfront get-distribution --id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --query 'Distribution.Status'"
          echo ""
          echo "After deployment, verify:"
          echo "  curl https://alanmarcero.com/api  (should return 200)"
          echo "  Direct Lambda URL should return 403"
